### ISSUE TITLE
pp_run all descends into .diagnostics directory

### ISSUE THREAD

**Issue by mkelley** [mommermi/photometrypipeline#19]
Hi Michael,

pp_run all descends into the .diagnostics directory and crashes:
```
RUN PIPELINE IN /disks/data0/data/lowell/data/20160212/phot/c2013a1/SDSS-R/.diagnostics
ERROR: cannot open file C_2013_A1_(Siding_Spring).gif
ERROR: cannot open file curveofgrowth.dat
Traceback (most recent call last):
  File "/home/msk/local/photometrypipeline/pp_run", line 390, in <module>
    fixed_aprad, source_tolerance)
  File "/home/msk/local/photometrypipeline/pp_run", line 114, in run_the_pipeline
    '_pp_conf.instrument_keys accordingly')
KeyError: 'cannot identify telescope/instrument; please update_pp_conf.instrument_keys accordingly'
```
Maybe this directory name should always be skipped?

**Comment by mommermi** [comment]
I agree! Consider it done!

**Comment by mommermi** [comment]
Mike, one more comment: if you use ``pp_run all``, please use the ``-prefix`` option so that the pipeline knows what your filename conventions are. In the case of LMI, you can use ``pp_run -prefix lmi. all``.
M

**Comment by mkelley** [comment]
Got it, thanks.
