### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by gordtulloch** [mommermi/photometrypipeline#54]
Hi there:

I installed your photometrypipline and ran into some issues that leads me to believe there's some code issues in the repository:

$ pp_run all
Traceback (most recent call last):
  File "/home/gtulloch/Dropbox/Astronomy/Projects/photometrypipeline/pp_run", line 402, in <module>
    diag.create_summary()
AttributeError: 'Registration_Diagnostics' object has no attribute 'create_summary'

If I go into the code and comment out that line, the code starts running through my data directory but dies on the following:

$ pp_run all

 NOTHING TO DO IN /home/gtulloch/Dropbox/Astronomy/Projects/photometrypipeline/data

 NOTHING TO DO IN /home/gtulloch/Dropbox/Astronomy/Projects/photometrypipeline/data/DXAND

 RUN PIPELINE IN /home/gtulloch/Dropbox/Astronomy/Projects/photometrypipeline/data/DXAND/B
Traceback (most recent call last):
  File "/home/gtulloch/Dropbox/Astronomy/Projects/photometrypipeline/pp_run", line 426, in <module>
    rerun_registration, asteroids)
TypeError: run_the_pipeline() missing 1 required positional argument: 'keep_wcs'

This seems like there's some code missing in the repository? I've attached the log but seems like it's not much help.

Thanks very much for making this available, if I can get it working it saves me a huge amount of work!

Regards,
  Gord

**Comment by gordtulloch** [comment]
Bump

**Comment by gordtulloch** [comment]
Also:

gtulloch@linuxdev:~/photometrypipeline/example_data$ pp_run all
Traceback (most recent call last):
  File "/home/gtulloch/photometrypipeline/pp_run", line 402, in <module>
    diag.create_summary()
AttributeError: 'Registration_Diagnostics' object has no attribute 'create_summary'
gtulloch@linuxdev:~/photometrypipeline/example_data$
